In [1]:
import numpy as np
x = np.array([[1, 2],
              [3, 4]])


In [2]:
s = x**2

In [3]:
s

array([[ 1,  4],
       [ 9, 16]])

In [6]:
np.sum(s,axis=0)

array([10, 20])

In [7]:
x*s

array([[ 1,  8],
       [27, 64]])

In [12]:
m = np.array([2,1])

In [16]:
s

array([[ 1,  4],
       [ 9, 16]])

In [17]:
m

array([2, 1])

In [18]:
s*m

array([[ 2,  4],
       [18, 16]])

In [19]:
np.empty(0)

array([], dtype=float64)

In [20]:
aa = np.empty(0)

In [22]:
aaa = np.append(aa,55)

In [23]:
aaa

array([55.])